import type { BulkPermission, BulkRecordType } from '@/lib/bulk/bulkActions'

export type BulkActionMatrixEntry = {
  recordType: BulkRecordType
  page: string
  component: string
  identifier: string
  storage: string
  allowedActions: string[]
  restrictedActions: string[]
  requiredPermission: BulkPermission
  selectAllMatching: 'supported' | 'visible-only' | 'deferred'
  lifecycleRisks: string[]
}

export const SKILLIFY_BULK_ACTION_MATRIX: BulkActionMatrixEntry[] = [
  {
    recordType: 'lead',
    page: '/dashboard/[workspaceSlug]/leads',
    component: 'components/dashboard/sales/LeadsClient.tsx',
    identifier: 'lead.id',
    storage: 'CRM preview/data source',
    allowedActions: [
      'Add tags',
      'Remove tags',
      'Assign owner',
      'Change source',
      'Archive',
      'Export',
    ],
    restrictedActions: [
      'Bulk convert leads',
      'Bulk create opportunities or sales',
      'Mark converted directly',
    ],
    requiredPermission: 'member',
    selectAllMatching: 'deferred',
    lifecycleRisks: ['Lead conversion must remain native lifecycle behavior.'],
  },
  {
    recordType: 'opportunity',
    page: '/dashboard/[workspaceSlug]/opportunities',
    component: 'components/dashboard/sales/OpportunitiesClient.tsx',
    identifier: 'opportunity.id',
    storage: 'CRM preview/data source',
    allowedActions: [
      'Add tags',
      'Remove tags',
      'Assign owner',
      'Change non-terminal stage',
      'Archive',
      'Export',
    ],
    restrictedActions: [
      'Mark won',
      'Mark lost without deterministic lifecycle rule',
      'Create sales records generically',
    ],
    requiredPermission: 'member',
    selectAllMatching: 'deferred',
    lifecycleRisks: [
      'Terminal stage changes can create related lifecycle effects.',
    ],
  },
  {
    recordType: 'sale',
    page: '/dashboard/[workspaceSlug]/sales-pipeline',
    component: 'components/dashboard/sales/SalesPipelineClient.tsx',
    identifier: 'deal.id',
    storage: 'Sales preview/data source',
    allowedActions: [
      'Add tags',
      'Remove tags',
      'Assign owner',
      'Change non-terminal stage',
      'Archive',
      'Export',
    ],
    restrictedActions: [
      'Mark won',
      'Create clients',
      'Bypass closed-won lifecycle rules',
    ],
    requiredPermission: 'member',
    selectAllMatching: 'deferred',
    lifecycleRisks: [
      'Closed-won behavior must use native sale lifecycle rules.',
    ],
  },
  {
    recordType: 'client',
    page: '/dashboard/[workspaceSlug]/clients',
    component: 'components/dashboard/clients/ClientsClient.tsx',
    identifier: 'client.id',
    storage: 'Client preview/data source',
    allowedActions: [
      'Add tags',
      'Remove tags',
      'Assign account manager',
      'Change health/status',
      'Archive',
      'Export',
    ],
    restrictedActions: [
      'Overwrite notes',
      'Alter addresses',
      'Merge clients',
      'Delete without confirmation',
    ],
    requiredPermission: 'member',
    selectAllMatching: 'deferred',
    lifecycleRisks: [
      'Client merge/address operations need dedicated business rules.',
    ],
  },
  {
    recordType: 'service-request',
    page: '/dashboard/[workspaceSlug]/service-requests',
    component:
      'components/dashboard/service-requests/ServiceRequestsClient.tsx',
    identifier: 'request.id',
    storage: 'Service request preview/data source',
    allowedActions: [
      'Assign/reassign',
      'Change priority',
      'Explicit reschedule',
      'Archive',
      'Export',
    ],
    restrictedActions: [
      'Bulk complete requests',
      'Overwrite descriptions or notes',
    ],
    requiredPermission: 'member',
    selectAllMatching: 'deferred',
    lifecycleRisks: [
      'Completion can have downstream service lifecycle effects.',
    ],
  },
  {
    recordType: 'task',
    page: '/dashboard/[workspaceSlug]/tasks',
    component: 'components/dashboard/tasks/TasksClient.tsx',
    identifier: 'task.id',
    storage: 'Task preview/data source',
    allowedActions: [
      'Assign/reassign',
      'Change priority',
      'Lifecycle-valid status change',
      'Explicit reschedule',
      'Archive/delete completed',
      'Export',
    ],
    restrictedActions: [
      'Silent due-date overwrite',
      'Invalid status transition',
    ],
    requiredPermission: 'member',
    selectAllMatching: 'deferred',
    lifecycleRisks: [
      'Task status changes must respect task lifecycle validation.',
    ],
  },
  {
    recordType: 'commerce-customer',
    page: '/dashboard/[workspaceSlug]/customers',
    component: 'components/commerce/CommerceCustomersPage.tsx',
    identifier: 'customer.id',
    storage: 'Workspace-scoped commerce preview storage',
    allowedActions: [
      'Add tags',
      'Remove tags',
      'Change customer type',
      'Change relationship status',
      'Archive',
      'Export',
    ],
    restrictedActions: [
      'Edit addresses',
      'Overwrite notes',
      'Modify derived metrics',
      'Delete with protected related records',
    ],
    requiredPermission: 'member',
    selectAllMatching: 'supported',
    lifecycleRisks: [
      'Status and type are distinct; revenue/order metrics are derived and not bulk editable.',
    ],
  },
  {
    recordType: 'product',
    page: '/dashboard/[workspaceSlug]/products',
    component: 'components/commerce/ProductCatalogPage.tsx',
    identifier: 'product.id',
    storage: 'Workspace-scoped commerce preview storage',
    allowedActions: [
      'Set active',
      'Set draft',
      'Archive',
      'Add/remove tags',
      'Change category/vendor',
      'Toggle inventory tracking',
      'Export',
    ],
    restrictedActions: ['Bulk price/cost overwrite', 'Erase variant inventory'],
    requiredPermission: 'member',
    selectAllMatching: 'supported',
    lifecycleRisks: ['Inventory tracking changes need explicit confirmation.'],
  },
  {
    recordType: 'order',
    page: '/dashboard/[workspaceSlug]/orders',
    component: 'components/commerce/OrdersPage.tsx',
    identifier: 'order.id',
    storage: 'Workspace-scoped commerce preview storage',
    allowedActions: [
      'Export',
      'Packing slips when supported',
      'Assign fulfillment owner when supported',
      'Validated fulfillment creation',
      'Archive eligible completed/cancelled',
    ],
    restrictedActions: [
      'Mark paid',
      'Mark shipped',
      'Mark delivered',
      'Mark completed',
      'Refund',
      'Cancel without dedicated lifecycle operation',
    ],
    requiredPermission: 'member',
    selectAllMatching: 'supported',
    lifecycleRisks: [
      'Payment, fulfillment, and total changes are lifecycle/financial operations.',
    ],
  },
  {
    recordType: 'fulfillment',
    page: '/dashboard/[workspaceSlug]/fulfillment',
    component: 'components/commerce/FulfillmentPage.tsx',
    identifier: 'fulfillment.id',
    storage: 'Workspace-scoped commerce preview storage',
    allowedActions: [
      'Assign/reassign',
      'Change priority',
      'Print packing slips/labels when supported',
      'Archive eligible records',
      'Export',
    ],
    restrictedActions: [
      'Generic mark shipped',
      'Generic mark delivered',
      'Overwrite tracking numbers',
    ],
    requiredPermission: 'member',
    selectAllMatching: 'supported',
    lifecycleRisks: ['Shipment states must use native fulfillment controls.'],
  },
  {
    recordType: 'automation',
    page: '/dashboard/[workspaceSlug]/automations',
    component: 'app/dashboard/[workspaceSlug]/automations/page.tsx',
    identifier: 'automation.id',
    storage: 'Automation API/database',
    allowedActions: [
      'Enable valid automations',
      'Disable',
      'Duplicate with confirmation',
      'Archive',
      'Export configuration',
    ],
    restrictedActions: ['Bulk run blindly', 'Enable invalid automations'],
    requiredPermission: 'admin',
    selectAllMatching: 'deferred',
    lifecycleRisks: ['Enable must run automation validation per record.'],
  },
  {
    recordType: 'execution',
    page: '/dashboard/[workspaceSlug]/executions',
    component: 'components/dashboard/executions/ExecutionsClient.tsx',
    identifier: 'execution.id',
    storage: 'Execution/run data source',
    allowedActions: [
      'Export',
      'Archive/clear eligible retained history',
      'Retry failed only with safe retry contract',
    ],
    restrictedActions: [
      'Fake retries',
      'Mutate successful results',
      'Retry running/pending executions',
    ],
    requiredPermission: 'member',
    selectAllMatching: 'deferred',
    lifecycleRisks: ['Retry must reuse the execution engine contract.'],
  },
  {
    recordType: 'template',
    page: '/dashboard/[workspaceSlug]/templates',
    component: 'app/dashboard/[workspaceSlug]/templates/page.tsx',
    identifier: 'template.id',
    storage: 'Template data source',
    allowedActions: [
      'Add/remove category or tags',
      'Duplicate',
      'Archive',
      'Publish/unpublish where validated',
      'Export',
    ],
    restrictedActions: ['Publish invalid templates'],
    requiredPermission: 'member',
    selectAllMatching: 'deferred',
    lifecycleRisks: ['Publish actions need validation and permission checks.'],
  },
  {
    recordType: 'member',
    page: '/dashboard/[workspaceSlug]/members',
    component: 'app/dashboard/[workspaceSlug]/members/MembersClient.tsx',
    identifier: 'member.id',
    storage: 'Workspace member API/database',
    allowedActions: [
      'Change role except protected owners',
      'Groups when supported',
      'Deactivate/remove eligible members',
      'Resend pending invitations',
    ],
    restrictedActions: [
      'Remove current user',
      'Remove last owner',
      'Demote all owners',
      'Non-admin owner/admin actions',
    ],
    requiredPermission: 'admin',
    selectAllMatching: 'deferred',
    lifecycleRisks: [
      'Ownership and access safety must be enforced server-side.',
    ],
  },
  {
    recordType: 'admin-user',
    page: '/dashboard/admin/users',
    component: 'app/dashboard/admin/users/page.tsx',
    identifier: 'user.id',
    storage: 'Admin API/database',
    allowedActions: ['Approved role changes', 'Activate/deactivate', 'Export'],
    restrictedActions: ['Unsafe destructive administration behavior'],
    requiredPermission: 'system-admin',
    selectAllMatching: 'deferred',
    lifecycleRisks: ['System-admin checks must be enforced server-side.'],
  },
]
