'use client'

import {
  Bot,
  Boxes,
  BrainCircuit,
  Calculator,
  Calendar,
  Check,
  CheckSquare,
  Clock,
  Database,
  FileText,
  GitBranch,
  Hash,
  HeartPulse,
  Mail,
  MessageSquare,
  Network,
  Split,
  Sparkles,
  Tags,
  TextCursorInput,
  UserPlus,
  Users,
  Wand2,
  Webhook,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

const NODE_ICON_MAP: Record<string, LucideIcon> = {
  bot: Bot,
  boxes: Boxes,
  brain: BrainCircuit,
  'brain-circuit': BrainCircuit,
  branch: GitBranch,
  calculator: Calculator,
  calendar: Calendar,
  chart: Network,
  check: Check,
  'check-square': CheckSquare,
  clock: Clock,
  database: Database,
  'database-zap': Zap,
  hash: Hash,
  'heart-pulse': HeartPulse,
  mail: Mail,
  message: MessageSquare,
  note: FileText,
  split: Split,
  'split-square': Split,
  sparkles: Sparkles,
  tags: Tags,
  text: TextCursorInput,
  'user-plus': UserPlus,
  users: Users,
  wand: Wand2,
  webhook: Webhook,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
}

export function getWorkflowNodeIcon(iconKey?: string | null): LucideIcon {
  if (!iconKey) return Workflow
  return NODE_ICON_MAP[iconKey] ?? Workflow
}
