import { normalizePreviewProduct } from '@/lib/commerce/previewCommerceStorage'
import type { CommerceProduct } from '@/lib/commerce/types'

const DEMO_CREATED_AT = '2026-01-15T12:00:00.000Z'

export function createDemoCommerceProducts(
  workspaceId: string,
): CommerceProduct[] {
  return [
    normalizePreviewProduct(
      {
        id: `demo_${workspaceId}_energy_drink`,
        workspaceId,
        name: 'Energy Drink - Original',
        description: 'Flagship canned drink sold by single unit and case.',
        status: 'ACTIVE',
        sku: 'ENERGY-ORIG',
        category: 'Beverages',
        vendor: 'Skillify Demo Supply',
        price: { amount: 3.99, currency: 'USD' },
        compareAtPrice: { amount: 4.99, currency: 'USD' },
        cost: { amount: 1.35, currency: 'USD' },
        taxable: true,
        trackInventory: true,
        inventoryQuantity: 18,
        lowStockThreshold: 24,
        hasVariants: true,
        variants: [
          {
            id: `demo_${workspaceId}_energy_original_12`,
            workspaceId,
            productId: `demo_${workspaceId}_energy_drink`,
            name: 'Original / 12 oz',
            optionValues: { Flavor: 'Original', Size: '12 oz' },
            sku: 'ENERGY-ORIG-12',
            status: 'ACTIVE',
            price: { amount: 3.99, currency: 'USD' },
            cost: { amount: 1.35, currency: 'USD' },
            inventoryQuantity: 10,
            createdAt: DEMO_CREATED_AT,
            updatedAt: DEMO_CREATED_AT,
          },
          {
            id: `demo_${workspaceId}_energy_berry_16`,
            workspaceId,
            productId: `demo_${workspaceId}_energy_drink`,
            name: 'Berry / 16 oz',
            optionValues: { Flavor: 'Berry', Size: '16 oz' },
            sku: 'ENERGY-BERRY-16',
            status: 'ACTIVE',
            price: { amount: 4.99, currency: 'USD' },
            cost: { amount: 1.75, currency: 'USD' },
            inventoryQuantity: 8,
            createdAt: DEMO_CREATED_AT,
            updatedAt: DEMO_CREATED_AT,
          },
        ],
        tags: ['demo', 'low stock'],
        createdAt: DEMO_CREATED_AT,
        updatedAt: DEMO_CREATED_AT,
      },
      workspaceId,
    ),
    normalizePreviewProduct(
      {
        id: `demo_${workspaceId}_subscription_box`,
        workspaceId,
        name: 'Subscription Box',
        description: 'Monthly curated product bundle placeholder.',
        status: 'DRAFT',
        sku: 'SUB-BOX',
        category: 'Subscriptions',
        vendor: 'Skillify Demo Supply',
        price: { amount: 39, currency: 'USD' },
        cost: { amount: 18, currency: 'USD' },
        taxable: true,
        trackInventory: false,
        hasVariants: false,
        tags: ['demo', 'subscription'],
        createdAt: DEMO_CREATED_AT,
        updatedAt: '2026-02-02T12:00:00.000Z',
      },
      workspaceId,
    ),
    normalizePreviewProduct(
      {
        id: `demo_${workspaceId}_apparel`,
        workspaceId,
        name: 'Branded Apparel',
        status: 'ACTIVE',
        sku: 'APPAREL',
        category: 'Merchandise',
        price: { amount: 28, currency: 'USD' },
        cost: { amount: 11, currency: 'USD' },
        taxable: true,
        trackInventory: true,
        inventoryQuantity: 64,
        lowStockThreshold: 10,
        hasVariants: false,
        tags: ['demo'],
        createdAt: DEMO_CREATED_AT,
        updatedAt: '2026-02-12T12:00:00.000Z',
      },
      workspaceId,
    ),
    normalizePreviewProduct(
      {
        id: `demo_${workspaceId}_wholesale_case`,
        workspaceId,
        name: 'Wholesale Case',
        status: 'ACTIVE',
        sku: 'CASE-24',
        category: 'Wholesale',
        price: { amount: 72, currency: 'USD' },
        taxable: true,
        trackInventory: true,
        inventoryQuantity: 0,
        lowStockThreshold: 5,
        hasVariants: false,
        tags: ['demo', 'wholesale'],
        createdAt: DEMO_CREATED_AT,
        updatedAt: '2026-03-04T12:00:00.000Z',
      },
      workspaceId,
    ),
    normalizePreviewProduct(
      {
        id: `demo_${workspaceId}_limited`,
        workspaceId,
        name: 'Limited Edition Product',
        status: 'ARCHIVED',
        sku: 'LIMITED-001',
        category: 'Seasonal',
        price: { amount: 49, currency: 'USD' },
        cost: { amount: 22, currency: 'USD' },
        taxable: true,
        trackInventory: false,
        hasVariants: false,
        tags: ['demo', 'seasonal'],
        archivedAt: '2026-04-01T12:00:00.000Z',
        createdAt: DEMO_CREATED_AT,
        updatedAt: '2026-04-01T12:00:00.000Z',
      },
      workspaceId,
    ),
  ]
}
